# -*- coding: utf-8 -*-
"""face_mask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V-E2rI_7cDFKRFZTvbi2xa7gbO5aha5Z
"""

from ultralytics import YOLO
import gradio as gr
import cv2
import numpy as np

# Load YOLOv8 model
model = YOLO("best.pt")

def detect_mask(image):
    image = cv2.cvtColor(np.array(image), cv2.COLOR_RGB2BGR)

    results = model(image)[0]

    violation_detected = False

    for box in results.boxes:
        cls_id = int(box.cls[0])
        conf = float(box.conf[0])
        label = model.names[cls_id]

        x1, y1, x2, y2 = map(int, box.xyxy[0])

        # Change colors based on class
        if label.lower() in ["no mask", "incorrect"]:
            color = (0, 0, 255)  # Red
            violation_detected = True
        else:
            color = (0, 255, 0)  # Green

        cv2.rectangle(image, (x1, y1), (x2, y2), color, 2)
        cv2.putText(image, f"{label} {conf:.2f}",
                    (x1, y1 - 10),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.6, color, 2)

    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    if violation_detected:
        return image, "🚨 Alert! Mask violation detected!"
    else:
        return image, "✅ All good. Proper mask usage."

iface = gr.Interface(
    fn=detect_mask,
    inputs=gr.Image(type="pil"),
    outputs=[gr.Image(), gr.Textbox()],
    title="Face Mask Detection System",
    description="Upload an image to check mask compliance."
)

iface.launch()